num1 = int(input("number 1: "))
num2 = int(input("number 2: "))
sum = num1 + num2
sub = num1 - num2
mul = num1 * num2
div = num1 / num2
print("Addition = ",sum)
print("Subtraction = ",sub)
print("Multiplication = ",mul)
print("Division = ",div)